import {
    defineConfigWithVueTs,
    vueTsConfigs,
} from '@vue/eslint-config-typescript';
import prettier from 'eslint-config-prettier/flat';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import importX from 'eslint-plugin-import-x';
import vue from 'eslint-plugin-vue';

export default defineConfigWithVueTs(
    vue.configs['flat/recommended'],
    vueTsConfigs.recommended,
    {
        plugins: {
            'import-x': importX,
        },
        settings: {
            // The solution config references both the app and the build-tooling
            // projects, so pointing at it covers every import in one pass.
            'import-x/resolver-next': [
                createTypeScriptImportResolver({
                    alwaysTryTypes: true,
                    project: './tsconfig.json',
                }),
            ],
        },
        rules: {
            // Single-word page and layout components are the convention here
            // (Home.vue, Contact.vue), and Inertia resolves pages by filename.
            'vue/multi-word-component-names': 'off',

            'vue/component-api-style': ['error', ['script-setup']],
            'vue/define-macros-order': [
                'error',
                { order: ['defineProps', 'defineEmits'] },
            ],
            'vue/prefer-true-attribute-shorthand': 'error',

            '@typescript-eslint/consistent-type-imports': [
                'error',
                {
                    prefer: 'type-imports',
                    fixStyle: 'separate-type-imports',
                },
            ],
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],

            'import-x/order': [
                'error',
                {
                    groups: [
                        'builtin',
                        'external',
                        'internal',
                        'parent',
                        'sibling',
                        'index',
                    ],
                    alphabetize: {
                        order: 'asc',
                        caseInsensitive: true,
                    },
                },
            ],
            'import-x/consistent-type-specifier-style': [
                'error',
                'prefer-top-level',
            ],
            'import-x/no-duplicates': 'error',

            // console.warn/error are used deliberately for optional-module
            // failures that must stay visible; console.log is not.
            'no-console': ['error', { allow: ['warn', 'error', 'info'] }],
            eqeqeq: ['error', 'always', { null: 'ignore' }],
            'object-shorthand': ['error', 'always'],
            'prefer-const': ['error', { destructuring: 'all' }],
            'no-var': 'error',
        },
    },
    {
        ignores: [
            // Third-party and build output.
            'vendor',
            'node_modules',
            'public',
            'storage',
            'bootstrap/ssr',
            '.codex-tmp',
            '_starter_v0/**',

            // Generated by Laravel Wayfinder from PHP routes.
            'resources/js/actions/**',
            'resources/js/routes/**',
            'resources/js/wayfinder/**',
        ],
    },
    prettier, // Turn off all rules that might conflict with Prettier
);
